spring:
    application:
        name: caller-service

server:
    port: 8080

resilience4j:
    retry:
        retryAspectOrder: 2
        instances:
            callerServiceRetry:
                # Max attempts before calling fallback
                max-attempts: 3
                # Duration between each call
                wait-duration: 2s

    circuitbreaker:
        circuitBreakerAspectOrder: 1
        instances:
            callerServiceRetry:
                # Checks the last 3 calls to decide the state of the circuit
                sliding-window-size: 3
                # If >50% of the last 3 calls fail -> opens the circuit
                failure-rate-threshold: 50
                # Stays opens for 10 seconds
                wait-duration-in-open-state: 10s
                # Then half-opens the circuit for 2 calls
                permitted-number-of-calls-in-half-open-state: 2

# logging:
#     level:
#         io.github.resilience4j.retry: DEBUG
#         io.github.resilience4j.circuitbreaker: DEBUG
